# ===============================================
# EXPERIMENT: ISBI - In-Domain
# MODEL M1: Baseline (Raw -> Scratch)
# ===============================================

# --- DATA ---
data:
  # Источник канонических данных
  prepared_data_root: "../prepared_data/isbi2012_v1_raw" 
  # Куда сохранять тайлы для этого конкретного эксперимента
  interim_data_root: "./interim_data/isbi_M1_baseline"
  
  # Отключаем feature bank, так как это baseline
  feature_bank:
    use: false

# --- MODEL ---
model:
  # Энкодер обучается с нуля (не использует веса ImageNet)
  encoder_weights: null
  
  # Адаптер не нужен, так как у нас 1-канальный вход и нет предобучения
  adapter:
    use: false

# --- LOGGING ---
# DEV: Можно добавить теги в MLflow для удобной фильтрации
logging:
  mlflow_tags:
    experiment_type: "A_InDomain"
    dataset: "isbi"
    model_type: "M1_Baseline"